version: '3.8'

services:
  php:
    image: php:7.4-apache
    container_name: php_container
    volumes:
      - ./index.php:/var/www/html/index.php
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php.rule=Host(`yourdomain.com`)"
      - "traefik.http.services.php.loadbalancer.server.port=80"

  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - "--api.insecure=true"  # Отключаем безопасный режим для API
      - "--providers.docker=true"
    ports:
      - "80:80"  # Перенаправляем порт 80 на Traefik
      - "8080:8080"  # Для доступа к панели управления Traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Монтируем сокет Docker


networks:
  net:

